/** Confirmed public facts for GAS Huy Hoàng. */
export const STORE = {
  name: "GAS Huy Hoàng",
  tagline: "An toàn cho mọi gia đình",
  address: "199 ĐT784, Ấp Thuận Tân, Truông Mít, Tây Ninh",
  hours: "Mở cửa 24 giờ",
  areas: ["Truông Mít", "Bàu Đồn", "Ngã ba Đất Sét", "Tầm Lanh", "Cầu Khởi"],
  offers: "Luôn luôn nhiều ưu đãi",
  gift: "Thu bếp cũ đổi bếp mới",
  raffle: "Rút thăm trúng thưởng mỗi năm",
  promises: [
    "Tư vấn miễn phí",
    "Giao hàng tận nơi",
    "Hỗ trợ nhanh 24/7",
    "Gas chính hãng",
    "Thu bếp cũ đổi bếp mới",
    "Rút thăm trúng thưởng mỗi năm",
  ],
  products: [
    { name: "Gas 12kg", description: "Phù hợp nhu cầu nấu ăn hằng ngày của gia đình.", icon: "cylinder" },
    { name: "Gas 45kg", description: "Dành cho quán ăn và nhu cầu sử dụng thường xuyên.", icon: "flame" },
    { name: "Van gas", description: "Tư vấn loại van phù hợp với bình và bếp đang dùng.", icon: "wrench" },
    { name: "Bếp gas", description: "Lựa chọn bếp mới phù hợp không gian và nhu cầu.", icon: "cookingPot" },
  ],
  steps: [
    { title: "Gọi hoặc nhắn Zalo", description: "Cho cửa hàng biết loại gas hoặc sản phẩm anh chị cần." },
    { title: "Xác nhận đơn hàng", description: "Cửa hàng xác nhận sản phẩm và địa chỉ giao." },
    { title: "Giao và lắp tận nơi", description: "Nhân viên giao hàng, lắp đặt và tư vấn sử dụng." },
  ],
  values: [
    { title: "Gas chính hãng, an toàn", description: "Chú trọng chất lượng và an toàn khi sử dụng." },
    { title: "Giao gas nhanh chóng", description: "Phục vụ tận nơi trong các khu vực lân cận." },
    { title: "Phục vụ tận tâm", description: "Tư vấn nhiệt tình trước và sau khi giao hàng." },
    { title: "Đồng hành cùng mọi nhà", description: "Hỗ trợ nhu cầu gas và bếp của gia đình." },
  ],
  shopUrl: "#",
  callDisplay: "0984 135 227",
  callTel: "tel:+84984135227",
  phoneDisplay: "0908 868 643",
  phoneTel: "tel:+84908868643",
  zaloDisplay: "0984 135 227",
  zaloUrl: "https://zalo.me/84984135227",
  mapsUrl: "https://maps.app.goo.gl/uT9Smi7HwfjcJzKB9",
  directionsUrl: "https://www.google.com/maps/dir/?api=1&destination=11.2036643,106.2860549",
  mapsEmbed: "https://www.google.com/maps?cid=13871117475713552749&hl=vi&output=embed",
  facebookUrl: "https://www.facebook.com/gashuyhoang.vn",
  pageTitle: "Gas Huy Hoàng — Cửa hàng gas Truông Mít, Tây Ninh",
  pageDescription:
    "GAS Huy Hoàng tại 199 ĐT784, Ấp Thuận Tân, Truông Mít, Tây Ninh. Mở cửa 24 giờ. Gọi 0984 135 227 hoặc 0908 868 643.",
} as const;
